[Fix] Plugin Welcome Page Design
anspress/anspress pull request #596
Opened 2023-02-20 04:29 UTC by mebishalnapit

This PR includes:

* Fixes the design of AnsPress Welcome page

2023-06-13 16:03 UTC, rahularyan requested changes

2023-06-13 16:03 UTC, rahularyan commented on package.json
> +		"node-sass": "^8.0.0",
Don't use node-sass, replace this with: https://www.npmjs.com/package/sass

2023-08-07 02:43 UTC, mebishalnapit commented
@rahularyan Conflicts have been resolved. Please check and confirm.

2023-08-07 02:48 UTC, rahularyan requested changes
@mebishalnapit This has to be rebased and and run PHPCS. Make sure package.json is not affected by this commit.

2023-08-09 03:36 UTC, closed without merging