[Fix] Syntax Highlighter addon is not working when Quick tags editor is enabled
anspress/anspress pull request #828
Opened 2023-08-11 03:47 UTC by mebishalnapit

This PR includes:

* Fixes the **Syntax Highlighter** addon/feature not working when Quick tags editor is enabled for Question and Answer

2024-02-21 16:54 UTC, rahularyan requested changes

2024-02-21 16:54 UTC, rahularyan commented on templates/functions.php
> +	if ( ap_opt( 'question_text_editor' ) || ap_opt( 'answer_text_editor' ) ) {
@mebishalnapit We have to remove this.

2024-02-22 04:13 UTC, mebishalnapit commented on templates/functions.php
> +	if ( ap_opt( 'question_text_editor' ) || ap_opt( 'answer_text_editor' ) ) {
@rahularyan Removed.

2024-02-22 09:51 UTC, rahularyan approved these changes

2024-02-22 09:51 UTC, merged